apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keycloak-pep.fullname" . }}
  labels:
    {{- include "keycloak-pep.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "keycloak-pep.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "keycloak-pep.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PEP_PROXY_PORT
              value: {{ .Values.service.port | quote }}
            - name: PEP_PROXY_IDM_HOST
              value: {{ .Values.config.idm.host | quote }}
            - name: PEP_PROXY_IDM_PORT
              value: {{ .Values.config.idm.port | quote }}
            - name: PEP_PROXY_IDM_SSL_ENABLED
              value: {{ .Values.config.idm.ssl | quote }}
            - name: PEP_PROXY_APP_HOST
              value: {{ .Values.config.app.host | quote }}
            - name: PEP_PROXY_APP_PORT
              value: {{ .Values.config.app.port | quote }}
            - name: PEP_PROXY_APP_ID
              value: {{ .Values.config.pep.app_id | quote }}
            - name: PEP_PROXY_USERNAME
              value: {{ .Values.config.pep.username | quote }}
            - name: PEP_PROXY_PASSWORD
              value: {{ .Values.config.pep.password | quote }}
            - name: PEP_PROXY_AUTH_ENABLED
              value: "true"
            - name: PEP_PROXY_PDP
              value: "idm"
            - name: PEP_PROXY_MAGIC_KEY
              value: "1234"
            - name: PEP_PROXY_DEBUG
              value: "true"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
