apiVersion: v1
kind: Service
metadata:
  name: {{ include "mosquitto.fullname" . }}
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mqtt
      protocol: TCP
      name: mqtt
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
    - port: 9001
      targetPort: websockets
      protocol: TCP
      name: websockets
  selector:
    {{- include "mosquitto.selectorLabels" . | nindent 4 }}