apiVersion: apps/v1
kind: Deployment
{{- $persistence := .Values.keycloak.persistence | default dict }}
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "keycloak.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "keycloak.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: keycloak
          image: "{{ .Values.keycloak.image.repository }}:{{ .Values.keycloak.image.tag }}"
          imagePullPolicy: {{ .Values.keycloak.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - exec /opt/keycloak/bin/kc.sh start-dev --import-realm
          env:
            - name: KEYCLOAK_ADMIN
              value: {{ .Values.keycloak.auth.adminUser }}
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: {{ .Values.keycloak.auth.adminPassword }}
            - name: KC_FEATURES
              value: "scripts"
            - name: KC_PROXY_HEADERS
              value: "xforwarded"
            - name: KC_HTTP_RELATIVE_PATH
              value: "/"
            - name: KC_HEALTH_ENABLED
              value: "true"
            - name: KC_METRICS_ENABLED
              value: "true"
            {{- if .Values.keycloak.extraEnvVars }}
            {{- toYaml .Values.keycloak.extraEnvVars | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /health/live
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 5
          volumeMounts:
            - name: realm-config
              mountPath: /opt/keycloak/data/import
            - name: storage
              mountPath: /opt/keycloak/data
            {{- if .Values.keycloak.extraVolumeMounts }}
            {{- toYaml .Values.keycloak.extraVolumeMounts | nindent 12 }}
            {{- end }}
      volumes:
        - name: realm-config
          configMap:
            name: {{ include "keycloak.name" . }}-realm
        - name: storage
        {{- if $persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "keycloak.fullname" . }}-data
        {{- else }}
          emptyDir: {}
        {{- end }}
        {{- if .Values.keycloak.extraVolumes }}
        {{- toYaml .Values.keycloak.extraVolumes | nindent 8 }}
        {{- end }}