{{- $persistence := .Values.keycloak.persistence | default dict }}
{{- if $persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "keycloak.fullname" . }}-data
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ $persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ $persistence.size | quote }}
  {{- if $persistence.storageClass }}
  storageClassName: {{ $persistence.storageClass | quote }}
  {{- end }}
{{- end }}