apiVersion: v2
name: keycloak-pep
description: A Helm chart for Kubernetes to deploy FIWARE PEP Proxy (Wilma).
type: application
version: 2.0.0
appVersion: "8.3.0"
home: https://github.com/fiware/pep-proxy
keywords:
  - keycloak
  - pep
  - wilma
  - Java
sources:
  - xxx
maintainers:
  - name: Felipe Roca 
    email: felipe@hopu.org
  - name: Alvaro Lopez
    email: alopezme@redhat.com
  - name: Stefan Wiedemann
    email: stefan.wiedemann@fiware.org